### ISSUE TITLE
Local template folder

### ISSUE THREAD

**Issue by dslagman** [wadewegner/sfdx-code-gen#1]
I tried putting .sfdx-templates folder in root directory of the sfdx project and on the C drive (windows) but in both cases I get the error that the specified template does not exist. I have the following file structure:

/.sfdx-templates
/.sfdx-templates/selector
/.sfdx-templates/selector/selector.cls
/.sfdx-templates/selector/selector.cls-meta.xml
/.sfdx-templates/selector/def.json

The json looks as following:
`{
  "vars": [
		"className",
		"sObjectName",
		"apiVersion"
  ],
  "files": [
    ["selector.cls", "cls"],
    ["selector.cls-meta.xml", "cls-meta.xml"]
  ],
  "bundle": false
}`

When I enter `sfdx waw:code:create -t selector -n AR_TypeTelwerkSjabloonSelector -v className=AR_TypeTelwerkSjabloonSelector,sObjectType=AR_Type_Telwerk_Sjabloon__c,apiVersion=42.0` I get the error: `ERROR: specified template 'selector' doesn't exist`.

**Comment by Szandor72** [comment]
Please put the .`sfdx-template` folder in your home directory. That would be `%UserProfile%` in windows or `C:\Users\myUserName`. Doing a `cd ~` in Powershell works, too.

**Comment by dslagman** [comment]
That worked! Thanks a lot.
